### PR TITLE
Adds Draconic Evolution Fusion Crafter

### PR DESCRIPTION
**Pull request by Prometheus0000**
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5157, https://github.com/GTNewHorizons/GT5-Unofficial/pull/203, https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/86.

I don't know how to do the rest though.
The casings and their recipes are in, but the textures don't show up like they should for some reason.
The schematics are in, and the textures should show up.
I have no idea how to add the recipe thing for the crafting as seen at https://github.com/GTNewHorizons/GT5-Unofficial/pull/203/files#diff-a8128596739521c74d8672ef8e3580c9689032c599dd7f8d99430d5bc93e9415R713 and https://github.com/GTNewHorizons/GT5-Unofficial/pull/203/files#diff-a8128596739521c74d8672ef8e3580c9689032c599dd7f8d99430d5bc93e9415R713 and https://github.com/GTNewHorizons/GT5-Unofficial/pull/203/files#diff-44c213063af7a2d91d174634daf1e3c3e5c4df39e0d16c902fcdf3a6893cfa4aR1358.

I gave up trying to get the controller part to work, so it needs the most work. It needs to check the right casings, and I'm not sure how many of the imports are actually used. And the assline recipe doesn't work because it can't import dreamcraft or whatever, so I can't check it. And the actual recipes for cores need adding/balancing. Someone who actually knows what they're doing could probably finish this off real quick?

### See: https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/17#issuecomment-1191969372

### CODE REVIEW

**Comment by Ethryan** [comment]
Why are you looking for ROBUST_NAQUADAH_ALLOY_**CASING**?
when the texture file is named ROBUST_NAQUADAH_ALLOY?

I think changing either of that should fix the textures not showing up.

**Comment by Prometheus0000** [comment]
Ok, the block textures show up now. Stupid mistake on my part.
image

**Comment by Prometheus0000** [comment]
When I try adding the assline recipe I get some kind of enum item error thing. I don't know if we want to keep DCores as UHV, but if so, the tiering is kinda pointless since you're at the end already, and we would want a research recipe done in TT, so there wouldn't be an error since the recipe would be done in another mod that does work. I'd like it if there was some discussion on that later. And the recipes as a whole.

Also, this recipe map thing is way too complicated for me to figure out. I'm also not sure how to change the texture the blocks change to without adding it to GT5U, since it's a completely different one (the black one) and the addMaintenanceToMachineList (for example) function requires an int.

**Comment by repo-alt** [comment]
I guess it should be refactored to structurelib now...

**Comment by Dream-Master** [comment]
> I guess it should be refactored to structurelib now...

yes this would be great

And i guess it need a bit reworked

**Comment by Dream-Master** [comment]
who can help me to finish this project ?

**Comment by kuba6000** [comment]
**OK. I think I have Finished Prometheus0000 work and also made some changes:**

- Overclock from casings is now time /= (amount of tiers above the recipe requirements + 1)
- There are only 2 fusion casings so I made 3+ casing tier require fusion casing MK II
- Changed name to Draconic Evolution Fusion Crafter (DE Core Crafter before)

**Some screenshots**

image
image
image
image
image
image
image
image
image

**Comment by Connor-Colenso** [comment]
Huzzah, very happy to see this finally finished after so long.

**Comment by boubou19** [comment]
time to yeet a whole quest tab then 😎

**Comment by Dream-Master** [comment]
Yea let final check the recipes and how you get the first schematic but yea very nice.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
