### PR TITLE
Fix solar panels and aspect generators not emitting energy without an adjacent GT tile

### PR DESCRIPTION
**Pull request by vlaetansky**
Actually fixes GTNewHorizons/Electro-Magic-Tools#20

### CODE REVIEW

**Comment by boubou19** [comment]
In what case this was causing issue? because it kinda makes sense to generate GT5U power only if there is a GT5U machine or cable next to the panel.

**Comment by repo-alt** [comment]
I guess because not just GT tiles may accept GT energy

**Comment by boubou19** [comment]
Yeah but in that case it's better to conver the others stuff to GT5U enet.

**Comment by repo-alt** [comment]
I guess "other stuff" in that case is some IC2 machine which is kinda hard to convert

**Comment by boubou19** [comment]
alright then

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
