### PR TITLE
Update ItemOneRing.java

### PR DESCRIPTION
**Pull request by draknyte1**
Adds a better tooltip.

### CODE REVIEW

**Review by glowredman — APPROVED** [review]

**Comment by Prometheus0000** [comment]
It doesn't appear to work

**Comment by glowredman** [comment]
Using '§' can sometimes lead to encoding issues. It's better to use the `\uxxxx` escape sequence or use EnumTextFormatting (not sure if thats the right class)

**Comment by draknyte1** [comment]
> Using '§' can sometimes lead to encoding issues. It's better to use the `\uxxxx` escape sequence or use EnumTextFormatting (not sure if thats the right class)

Yeah, think that’s it. 
I just knocked this together in my phone in 5 minutes while on a train, lol.

**Comment by Dream-Master** [comment]
@draknyte1 Can you fix this with your Phone and send a changed version ?

**Comment by draknyte1** [comment]
3B9B5835-56B0-4BB7-8407-EA9BE835EAB2

Appears to work fine. Feel free to have @Prometheus0000 change the text as necessary before merging.

**Comment by Prometheus0000** [comment]
BTW this means the commit (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6839/commits/e9aed9eacc794ff6dfe01f8bb0df4c9c21722d7e) I did should be reverted. Can you revert single commits?

I also need to add some info to the quest about what it does, but that's a different thing.

**Comment by draknyte1** [comment]
You can revert a single commit or a whole PR.

**Comment by draknyte1** [comment]
Refer to here if you wanna change the colour - https://github.com/eldariamc/client/blob/c01d23eb05ed83abb4fee00f9bf603b6bc3e2e27/src/main/java/net/minecraft/util/EnumChatFormatting.java#L9

**Pull request merged**
