### PR TITLE
Update buildscript

### PR DESCRIPTION
**Pull request by Caedis**
+update deps and nuke repositories.gradle

### CODE REVIEW

**Comment by miozune** [comment]
Can you also remove `.github/scripts` while you're at it?

**Comment by Caedis** [comment]
Done

**Review by miozune — APPROVED** [review]

**Comment by Caedis** [comment]
Guess I should also wait for an admin's review before merging

**Comment by miozune** [comment]
no, you can just merge it

**Comment by Caedis** [comment]
Gotcha

**Pull request merged**
