### PR TITLE
removed IC2BasicSource due to buggyness with new cables

### PR DESCRIPTION
**Pull request by bartimaeusnek**
https://github.com/GTNewHorizons/NewHorizons/issues/3731

also reformatted base tiles

### CODE REVIEW

**Comment by mitchej123** [comment]
What's the issue with it being an ic2 power source?  This seems super hacky without a clear benefit.

**Comment by mitchej123** [comment]
Hmm, we should fix the scanner output ideally instead of hacking together a non compliant energy source.

**Comment by bartimaeusnek** [comment]
@mitchej123 the solars have a build in conversion to GT, (which differs a lot from the cables ones) but the cables override that and use yours, which leads to explosions. (i.e. the Aqua Solar Panel SHOULD output 30EU/t at rain, 2A 30EU/t at thunderstorm, but since your cable convert the energy, they both output 512EU/t)

**Comment by richardhendricks** [comment]
Wouldn't that cause problems with any multiamp output, like battery buffers?

**Comment by Dream-Master** [comment]
we test it in the next version :)

**Pull request merged**
