### PR TITLE
 Make one ring be destroyed after 27+ hours to prevent collecting absurd amounts of warp.

### PR DESCRIPTION
**Pull request by Prometheus0000**
Might need to be lowered or raised, if you can still collect too much or not enough warp. You can always use
another ring and start collecting more though.

BTW, the amount on the ring is 1000 to be destroyed.

### CODE REVIEW

**Comment by bartimaeusnek** [comment]
I don't like the idea of the ring destroying itself. IMO we should work more with client effects here, i.e. Sunburned effect from thaumcraft or similar, something that *only affects the player*.

**Comment by Prometheus0000** [comment]
The idea is to stop them building up insane amounts of warp, because they're too stupid to take the ring off, or don't care about the effect it has on others.

If you want to add more thaumcraft warp effects, that's fine. If you want me to add them to the ring, I wouldn't know how. Also, I doubt visual effects will get them to take it off if they won't take it off with withers spawning.

**Comment by Alastors** [comment]
Dead PR, two years is enough time to say this is clearly not happening

**Comment by Dream-Master** [comment]
> Dead PR, two years is enough time to say this is clearly not happening

I say when a pr is dead not you. 😠

**Pull request closed without merging**
